### ISSUE TITLE
Problem with 2004 image?

### ISSUE THREAD

**Issue by lwsrbrts** [michawets/WVDTemplates#2]
https://github.com/michawets/WVDTemplates/blob/09a25a731a1cc7a4d70b04e1c25164c3ed649538/Hostpool/azuredeploy.json#L172

Hi Micha, appreciate this probably isn't something you expected an issue to be raised for and it's probably completely out of your control but I've been trying to deploy this template over the last 24-36 hours but the session hosts were never accessible.

The problem manifests primarily as simply not being able to connect to the host pool/session hosts via either the Remote Desktop or HTML5 clients. Poking through the host pool the session hosts report as "Unavailable" immediately after build and flip-flap a few times between available and unavailable before settling on unavailable. If given a reboot, the VMs then report as available and stay as such but it is still not possible to connect to the host pool.

I'm sure the problem is image related since changing to `19h2-evd-o365pp` results in successful connections. Hopefully MS update the image and fix it soon.

Just thought I'd let you/visitors know.

**Comment by michawets** [comment]
Hi @lwsrbrts ,

This is indeed a bug in the 2004 release, but it is resolvable quite quickly:
In my workshop, you can find the fix as well 😊 : https://aka.ms/wvdworkshop ➡ 

📌

    At this moment (17/06/2020), there is a bug in the Windows 10 2004 version.
    When connecting to WVD, you will get an error in the client:
    Error code: 0x3000047
    To resolve this, you must execute this on all VMs running Windows 10 2004 and restart the VM:

    Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\rdp-sxs" -Name "fReverseConnectMode" -Value 1 -Type DWord -Force

**Comment by lwsrbrts** [comment]
Aha! Well, that answers that then! I'm glad there's a simple answer. I found my way to your Github repos without going via the Workshop page so I "missed the memo" so to speak.

Thank you!

**Comment by michawets** [comment]
You're welcome @lwsrbrts 
I added the link to the workshop at the root readme as well 😊👍
